In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import animation
from IPython.display import display, Image
import numpy as np

# Problem solving (in python)

In the first lab you revised the level 4 python 'introduction to computational physics' course.

In this course we will go further both with your python code 'knowledge' but also with your understanding of how to approach physics (or any other) problem via computational methods. In code, as with most tools, there are many methods of reaching the 'correct' answer.  We want you to be able to not just code what you have been told to, but to be able to think creatively about how best to solve a problem.

We therefore want to introduce you today to how to problem solve using code.

We will look at a couple of simple problems for which will not use any special packages other than numpy arrays (we could do this entirely with list notation but numpy array makes maths more straightforward so we will use this for today).

# Problem A

For our first problem we will think about how to sort an array. This seems easy but is actually a fundamental and difficult coding problem with many solutions. We will try today to think of as many solutions as we can.

In [ ]:
array1a = np.array([2,1])

Sort this array in acsending order using these steps:

    1) Find the first element of the array
    2) Find the second element of the array
    3) Compare the elements
    4) Reorder the array if necessary
    5) Print the new array

In [ ]:
# Answer here
a = array1a[0]
b = array1a[1]
if a > b:
  array1a[0] = b
  array1a[1] = a
print(array1a)

[1 2]


Does your code work for this array? Copy and paste it below and print out the array.

In [ ]:
array1a = np.array([3,2,1])

In [ ]:
# Answer here
a = array1a[0]
b = array1a[1]
if a > b:
  array1a[0] = b
  array1a[1] = a
print(array1a)

[2 3 1]


Swapping just elements 1 and 2 obviously does not work here. But you could continue to swap elements like this:

* Initial array:

[ 3 2 1 ]

* Now we compare and swap elements:

[ <span style='color:Blue'> 3 2 </span> 1 ]  Compare first two elments

  [ <span style='color:Red'> 2 3 </span> 1 ]  Swap them if nec.

  [ 2 <span style='color:Blue'> 3 1 </span> ]  Compare next two elments

  [ 2 <span style='color:Red'> 1 3 </span> ]  Swap them if nec.

[ <span style='color:Blue'> 2 1 </span> 3 ]  Return to begining and compare first two elments

  [ <span style='color:Red'> 1 2 </span> 3 ]  Swap them if nec.

  [ 1 <span style='color:Blue'> 2 3 </span> ]  Compare next two elments

  [ 1 <span style='color:Green'> 2 3 </span> ]  Swap them if nec.

* Final array:

[ 1 2 3 ]

We will use this to code our first sorting algorithm.

To develop a first draft algorithm you do <b>NOT</b> need to know much code.

In fact it is often best to approach the problem by drawing, or writing bullet points - these are examples of <b>Pseudocode</b>.

<b>Pseudocode</b> is the name for any code-like process. You define the rules so it is a more flexible starting point. E.g. you don't need to remember ':' in python or ';' in C. You can choose to indent if not etc.

As an example I might write out the first routine for the array [ 2 1 ] as:

    i = first element
    j = second element
    compare i to j
    if i is greater than j
        swap the elements

I like to indent in my pseudocode as it is clearer to me - but you might not. It is entirely up to you.

You will now write out the algorithm above for sorting an array in your own pseudocode.  The one catch is that your algorithm must work for any size array. Consider the array:

    [ 4 2 3 1 ]
    
Think about how the steps above might apply to this array. It might help to write it out in the same way as I did above. The code below will help you start to write this - turn it to markdown to make the colours appear.  

In [ ]:
# Steps for a 4 element array

* Initial array:

[ 4 2 3 1 ]

* Compare first two elements and swap if necessary
[ 4 2 3 1 ]
[ 2 4 3 1 ]
* Compare next two elements (4 3) and swap if necessary
[ 2 4 3 1 ]
[ 2 3 4 1 ]
* Compare next two elements (4 1) and swap if necessary
[ 2 3 4 1 ]
[ 2 3 1 4 ]
* Go back to beginning and compare first two elements ( 2 3 ) again and swap if necessary
[ 2 3 1 4 ]
[ 2 3 1 4 ]
* Compare next two elements (3 1) and swap if necessary
[ 2 3 1 4 ]
[ 2 1 3 4 ]
* Compare next two elements (3 4) and swap if necessary
[ 2 1 3 4 ]
[ 2 1 3 4 ]
* Go back to beginning and compare first two elements (2 1) again and swap if necessary
[ 2 1 3 4 ]
[ 1 2 3 4 ]
* Compare next two elements (2 3) and swap if necessary
* Compare next two elements (3 4) and swap if necessary

* Final array:

[ 1 2 3 4 ]


SyntaxError: invalid syntax (<ipython-input-6-5692138e2449>, line 3)

How many for loops does your code need?

In [ ]:
# Answer here
'My code needs two for loops but it needs to loop through the code 3 times to get to the final answer'

Write out your pseudocode.

In [ ]:
from ast import AugAssign
# Pseudocode space
Loop over elements in the array
  i = first element
  j = second element
  compare i to j
    if i is greater than j
      swap elements
  i = second element
  j = third element
  compare i to j
    if i is greater than j
      swap elements
  i = third element
  j = fourth element
  compare i to j
    if i is greater than j
      swap elements
Check if the array is in the right order
  if not loop through again and repeat same steps as above, then do the same sort check
  else end the loop


SyntaxError: invalid syntax (<ipython-input-1-2a7d21e258ed>, line 3)

Now convert your pseudocode into python and write our your sorting algorithm.  Print the array at each step in your sorting algorithm.

In [ ]:
array1a = np.array([3,2,1])
print("Initial array :", array1a)

# Answer here
for j in range(0,len(array1a)-1):
  for i in range(0,len(array1a)-1):
    a = array1a[i]
    b = array1a[i+1]
    if a > b:
      array1a[i] = b
      array1a[i+1] = a
    print(array1a)


Initial array : [3 2 1]
[2 3 1]
[2 1 3]
[1 2 3]
[1 2 3]


This type of sort is called a bubble sort. However, our sort is non-optimised (you can see that we reach the correct answer long below we stop iterating the code. Can you think of ways to make this code more efficient?

In [ ]:
array1a = np.array([3,2,1])
print("Initial array :", array1a)

# Answer here
order = np.array(sorted(array1a))

for j in range(0,len(array1a)-1):
  for i in range(0,len(array1a)-1):
    # Add break statement in to stop code when array is in order
    if (array1a == order).all():
      break
    a = array1a[i]
    b = array1a[i+1]
    if a > b:
      array1a[i] = b
      array1a[i+1] = a
    print(array1a)

Initial array : [3 2 1]
[2 3 1]
[2 1 3]
[1 2 3]


## Lessons learned
* Writing a good algorithm is like solving a puzzle - it is about creatively thinking of solutions which will work for the task at hand.
* Pseudocode is a valuble tool for thinking about how to approach an algorithm - feel free tobring pen and paper to draw/write pseudocode to help you with this course.
* Figure out the approach you want to take and then think about how to explicitly code that approach in the python language.

# Problem B

For our second problem you will calculate the 'median' (middle value) of an array.

In [ ]:
array1b=np.array([1,2,3])

B) What is the median of this array?  No code - just write it down.

In [ ]:
# Answer here
'The answer is 2'

Even though you worked this out in your head you probably had a few lines of reasoning which you might not have realised you were consiously making. These steps might be sumarised as (not in correct order):

<div class="alert-success">
1. Check if your array is sorted.
</div>

<div class="alert-info">
2. Report the value of the array which coresponds to this middle index.
</div>

<div class="alert-danger">
3. Count the number of data points in your array.
</div>

<div class="alert-warning">
4. Find the index of the middle value.
</div>

How many different ways can you order the boxes above to still give you a recipe for finding the middle of our array above? (e.g. 1-2-3-4 - does this work?)

In [ ]:
# Answer here:
print('1-3-4-2 and 3-1-4-2 works, I do not think any other ordering works')

Choose a method and code it up.  You may NOT use np.size, len(array), or np.sort. You may use your sorting algorithm from above but you must figure out the size of the array yourself.

In [ ]:
array1b=np.array([1,2,3])

# Work out length of array
len_arr = 0
for i in array1b:
    len_arr+=1

# Check if array is sorted
order = np.array(sorted(array1b))

for j in range(0,len_arr-1):
  for i in range(0,len_arr-1):
    # Add break statement in to stop code when array is in order
    if (array1b == order).all():
      break
    a = array1b[i]
    b = array1b[i+1]
    if a > b:
      array1b[i] = b
      array1b[i+1] = a

# Find index of middle value
middle = np.floor_divide(len_arr,2)

# Find value of middle index
middle_value = array1b[middle]
print('Median is %s' % middle_value)

Median is 2


Verify you method also works for...

In [ ]:
array1b=np.array([1,2,3,4])

In [ ]:
# Answer here
# Work out length of array
len_arr = 0
for i in array1b:
    len_arr+=1

# Check if array is sorted
order = np.array(sorted(array1b))

for j in range(0,len_arr-1):
  for i in range(0,len_arr-1):
    # Add break statement in to stop code when array is in order
    if (array1b == order).all():
      break
    a = array1b[i]
    b = array1b[i+1]
    if a > b:
      array1b[i] = b
      array1b[i+1] = a

# Find index of middle value
middle = np.floor_divide(len_arr,2)

# Find value of middle index
middle_value = array1b[middle]
print('Median is %s' % middle_value)

Median is 3


If it does not then rewrite it to make it work for both odd and even valued arrays

In [ ]:
# Answer here
# Work out length of array
len_arr = 0
for i in array1b:
    len_arr+=1

# Check if array is sorted
order = np.array(sorted(array1b))

for j in range(0,len_arr-1):
  for i in range(0,len_arr-1):
    # Add break statement in to stop code when array is in order
    if (array1b == order).all():
      break
    a = array1b[i]
    b = array1b[i+1]
    if a > b:
      array1b[i] = b
      array1b[i+1] = a

# Find index of middle value
if len_arr % 2 == 0:
  middle = int(len_arr / 2)
  middle_value = (array1b[middle] + array1b[middle-1]) / 2
else:
  middle = np.floor_divide(len_arr,2)
  middle_value = array1b[middle]

print('Median is %s' % middle_value)

Median is 3.5


Could your code be more effficient - if you had chosen a different order to your algorthm could you have combined opperations such that fewer calculations were made?

In [ ]:
array1b=np.array([1,2,3,4])

# Answer here
# Work out length of array
len_arr = 0
for i in array1b:
    len_arr+=1

# Check if array is sorted
array1b = np.array(sorted(array1b))

# Find index of middle value
if len_arr % 2 == 0:
  middle = int(len_arr / 2)
  middle_value = (array1b[middle] + array1b[middle-1]) / 2
else:
  middle = np.floor_divide(len_arr,2)
  middle_value = array1b[middle]

print('Median is %s' % middle_value)

Median is 2.5


## Lessons learned
* There is rarely 'one way' to get the correct answer but there may be better ways
    * Use Pseudocode as a tool to think about how best to approach the problem before you start to code in python
* Consider all the properties of your data - could they be even or odd valued, do they have missing values, what 'data types' have been used - make sure to define 'test cases' for yourself to test your code works in a general way

# Problem C

For the third problem we will compare two words to identify if they are anagrams.

Consider the three sets of words:

    EARTH - HEART
    CAT - DOG
    DORMITORY - DIRTY ROOM
    
Here we will write some programs which compare these words and identify if they are anagrams by way of a boolen (True, False).

There are 4 ways you could do this that we will explore:
    1. Test that each character in word 1 actually occurs in word 2.
    2. Sort the letters in the word alphebetically and compare.
    3. Create a complete list of all the possible strings from word 1 and then compare this list with word 2. (NOTE - only test this with short words!)
    4. Count the number of times each character occurs in each word and then compare the result.

Write an algorithm for methods 1, 2 and 4 above. Method 3 is more advanced and has been written for you - you do not need to code it but should instead think about <b>how</b> you might code it.  How do the number of calculations performed by each method differ (give approximate answers - you don't need to count every single calculation)?

In [ ]:
# Answer here - method 1
def solution1(s1,s2):

  # remove any spaces and lower the case of s1 and s2
  s1 = s1.replace(' ','').lower()
  s2 = s2.replace(' ','').lower()

  count = 0
  # loop over letters in s1 and check if it is in s2. If True then add 1 to the count
  for i in range(0,len(s1)):
    if s1[i] in s2:
      count+=1
  # Check s1 and s2 are the same length
  if count == len(s2):
    matches = True
  else:
    matches = False

  return matches

print(solution1('earth', 'heart'))


True


In [ ]:
# Answer here - method 2
def solution2(s1, s2):

  # remove any spaces and lower the case of s1 and s2
  s1 = s1.replace(' ','').lower()
  s2 = s2.replace(' ','').lower()

  # Sort s1 and s2
  sorted_s1 = sorted(s1)
  sorted_s2 = sorted(s2)

  # test if the two words are the same
  if sorted_s1 == sorted_s2:
    matches = True
  else:
    matches = False

  return matches

print(solution2('DORMITORY', 'dirty room'))

True


In [ ]:
# Solution for (method 3) using itertools - recursion, generators etc is a way to
# solve this problem but we will look at those techniques in a few weeks time
def anagramSolution3(s1,s2):
    import itertools

    alist1 = list(s1)
    alist2 = list(s2)

    #convert letetrs to numbers and write factorial
    no_of_ways=np.math.factorial(len(alist1))
    print('no. of solutions :', no_of_ways)
    permutations = list(itertools.permutations(alist1))

    matches = False
    for i in permutations:
        print(i)
        if list(i) == alist2:
            matches = True
            return matches

    return matches

print(anagramSolution3('dog','cat'))

# O(n!)

no. of solutions : 6
('d', 'o', 'g')
('d', 'g', 'o')
('o', 'd', 'g')
('o', 'g', 'd')
('g', 'd', 'o')
('g', 'o', 'd')
False


In [ ]:
from sys import flags
# Answer here - method 4  Count the number of times each character occurs in each word and then compare the result.
def solution4(s1, s2):

  # remove any spaces and lower the case of s1 and s2
  s1 = s1.replace(' ','').lower()
  s2 = s2.replace(' ','').lower()

  # create numpy array of zeros to store number of times a letter appears
  a = np.zeros(len(s1))
  b = np.zeros(len(s2))

  # if the two words are not of the same length they cannot be anagrams
  if len(a) != len(b):
    matches = False
    return matches

  # loop over each word in s1 and count the number of times it appears in s1 and s2
  for i in range(0,len(s1)):
    a[i] = s1.count(s1[i])
    b[i] = s2.count(s1[i])

  # Check that a and b are the same to return true
  if a.all() == b.all():
    matches = True
  else:
    matches = False

  return(matches)

print(solution4('dirty room', 'dormitory'))

True


We tend to consider the number of calculations or steps in your code as a mark of its efficiency. We use the 'order of magnitude' notation big 'O' to report this.

In these cases above you worked out roughly how many calculations were done. In big O notation we would conclude this:

1. Two nested for loops are required e.g. for i in word 1 then loop through word 2 - so this is a O(n${^2}$) algorithm

2. The comparison is quick but the sort is again a two nested for loop operation (if using a bubble sort) so this dominates the process and it is again an O(n$^{2}$) algorithm

3. Search for each possible string combination rewuires n*(n-1)*(n-2)*(n-3)*...*1 operations which = n!. n! is even larger than n${^2}$ for big n  (O(n!)). This is not efficient for us though this approach might be the most familiar to humans as we try to make words from anagrams.

4. There are 26 letters in the alphabet so this algorithm only required that we go through one for loop and simply add a number when a letter turns up so this opertation is actually linear O(n). This is probably the last thing you would have thought of but it is the most efficient process.

## Lessons learned
* Take time to consider different methods of solving a problem - no need ot rush to code
* Consider what might be best for your algorithm - e.g. is it a one-off such that brute force works, does it ned to be generalised so it can work in many situations, does it need to be quick?

# Problem D - optional extra

For our final problem you will find the largest product in a grid which can be made by any four adjacent numbers.

The numbers could be adjacent vertically, horizontally or diagnoally.

In [ ]:
# Here I am generating a 10 by 10 grid. You will search this grid for the answer.

grid=np.zeros((10,10))

np.random.seed(10)
for i in range(0,10):
    for j in range(0,10):
        grid[i,j]=round(np.random.uniform(0,100))

print(grid)

[[77.  2. 63. 75. 50. 22. 20. 76. 17.  9.]
 [69. 95.  0. 51. 81. 61. 72. 29. 92. 71.]
 [54. 14. 37. 67. 44. 43. 62. 51. 65. 60.]
 [81. 52. 91. 32.  9. 30. 11. 83.  5. 63.]
 [55. 82. 20. 86. 35. 75. 30. 88. 33. 17.]
 [39.  9. 82. 15. 38. 94. 99. 46. 83. 25.]
 [60. 90. 53. 59.  4. 36.  8. 31. 33. 77.]
 [ 4. 43. 31. 64. 35.  4. 88. 76. 88. 42.]
 [61. 51. 60. 26. 30.  3. 30. 24. 56. 57.]
 [48. 29.  6. 98. 34. 50. 98. 44. 32. 52.]]


In [ ]:
# Answer here

# Number of points to use
adj = 4

# Horizontal
hor = np.zeros((len(grid), len(grid)-adj+1))
# Loop over the rows and in each row loop over the number
# of elements in the row. Find the product of asdjacent
# Horizontal numbers
for i in range(0,len(grid)):
  for j in range(0,len(grid[0])-adj+1):
    b = grid[i][j:j+adj]
    hor[i,j] = np.prod(b)

# Vertical
# Use the transpose to transform the grid so can reuse code
grid_t = grid.T
vert = np.zeros((len(grid_t), len(grid_t)-adj+1))
# Loop over the rows and in each row loop over the number
# of elements in the row. Find the product of asdjacent
# Horizontal numbers
for i in range(0,len(grid_t)):
  for j in range(0,len(grid_t[0])-adj+1):
    b = grid_t[i][j:j+adj]
    vert[i,j] = np.prod(b)

# Diagonal
# Sort out the indexes to loop over. Start in top left corner and work to
# bottom right corner
start_ele = -grid.shape[0]+1
end_ele = grid.shape[1]

# Sort out storing largest products for each diagnonal
num_points = abs(start_ele) + abs(end_ele)
diags1 = np.zeros(num_points)

# Start at top left, if the diagonal has more than 4 points then work out
# the product. Find the product for all instances in that diagonal and
# record. Find the max product in that array and store. Only find the
# mad product if the diagonal has 4 points
for i in range(start_ele,end_ele):
  a = np.array(grid[::-1,:].diagonal(i))
  if len(a) > adj:
    test = np.zeros(len(a)-adj+1)
    for j in range(0,len(a)-adj+1):
      test[j] = np.prod(a[j:j+adj])
    diags1[i+abs(start_ele)] = np.max(test)
  elif len(a) == adj:
    diags1[i+abs(start_ele)] = np.prod(a)

# Do the same but start at the top right corner
start_ele = grid.shape[1]-1
end_ele = -grid.shape[0]

num_points = abs(start_ele) + abs(end_ele)
diags2 = np.zeros(num_points)

diags2 = np.zeros(19)
for i in range(start_ele,end_ele,-1):
  a = np.array(grid.diagonal(i))
  if len(a) > adj:
    test = np.zeros(len(a)-adj+1)
    for j in range(0,len(a)-adj+1):
      test[j] = np.prod(a[j:j+adj])
    diags2[i+abs(start_ele)] = np.max(test)
  elif len(a) == adj:
    diags2[i+abs(start_ele)] = np.prod(a)

# Find the maximum from all 4 arrays
max_prod = np.asarray([hor.max(), vert.max(), diags1.max(), diags2.max()])
print('The largest product in a grid which can be made by any four adjacent numbers is %s' % int(max(max_prod)))


The largest product in a grid which can be made by any four adjacent numbers is 40496274


In [ ]:
# Hint 1

# One method would be to treat each sequence separately and then loop over elements.
# Consider what to do at the boundaries

In [ ]:
# Hint 2 - pseudocode

# max results array is same size as grid
# max method array is same size as grid
# number your methods for string in the method array
# 1. horizontal right, 2. horizontal left
# 3. vertical top, 4. vertical bottom
# 5. 45 degrees, 6. 135 degrees, 7. 225 degrees, 8. 315 degrees
# pad array with 3 extra rows and columns of zeros in each direction
# for each x element in array from 4 to :-4
#   for each y element in array from 4 to :-4
#       calculate the product for each method
#       store the maximum product and it's corresponding method in the results and mthod grid
# find max of results grid and report index
# find this index in method grid
# woop!