# Problem D - challenging

For our final problem you have a grid of numbers. You must find the largest product that can be made by any four numbers in a line. (The product is the multiplication of all 4 numbers).

The line of numbers could be a vertical, horizontal or diagonal line (same rules as a wordsearch). 

In [3]:
# Here I am generating a 10 by 10 grid. You will search this grid for the answer. 
import numpy as np

grid=np.zeros((10,10))

np.random.seed(10)
for i in range(0,10):
    for j in range(0,10):
        grid[i,j]=round(np.random.uniform(0,100))

print(grid)

[[77.  2. 63. 75. 50. 22. 20. 76. 17.  9.]
 [69. 95.  0. 51. 81. 61. 72. 29. 92. 71.]
 [54. 14. 37. 67. 44. 43. 62. 51. 65. 60.]
 [81. 52. 91. 32.  9. 30. 11. 83.  5. 63.]
 [55. 82. 20. 86. 35. 75. 30. 88. 33. 17.]
 [39.  9. 82. 15. 38. 94. 99. 46. 83. 25.]
 [60. 90. 53. 59.  4. 36.  8. 31. 33. 77.]
 [ 4. 43. 31. 64. 35.  4. 88. 76. 88. 42.]
 [61. 51. 60. 26. 30.  3. 30. 24. 56. 57.]
 [48. 29.  6. 98. 34. 50. 98. 44. 32. 52.]]


In [4]:
# Answer here


In [5]:
# Hint 1

# One method would be to treat each sequence separately and then loop over elements.
# Consider what to do at the boundaries

In [8]:
# Hint 2 - pseudocode

# max results array is same size as grid
# max method array is same size as grid
# number your methods for string in the method array 
# 1. horizontal right, 2. horizontal left
# 3. vertical top, 4. vertical bottom
# 5. 45 degrees, 6. 135 degrees, 7. 225 degrees, 8. 315 degrees
# pad array with 3 extra rows and columns of zeros in each direction 
# for each x element in array from 4 to :-4
#   for each y element in array from 4 to :-4
#       calculate the product for each method
#       store the maximum product and it's corresponding method in the results and method grid
# find max of results grid and report index
# find this index in method grid
# woop!