# Problem A

For our first problem we will think about how to sort an array. This seems easy but is actually a fundamental and difficult coding problem with many solutions. We will try today to think of as many solutions as we can. Sure, many of these solutions are available to you (e.g. the built-in function `sorted`), but someone had to code that up, and there are some cases where it may not be the "optimal" solution .... Sorting arrays is also a *really* common coding interview question so it's good to try coding sorting algorithms and will get us back into the practice of coding problem solving

**PLEASE NOTE: We are well aware that you can copy and paste a sorting algorithm from the internet. You will not learn anything from doing so (and it will not help you in the assessments that will follow). Although a professional coder will use the internet often, they do so from having a lot of experience and can quickly understand and discard "bad" options. Please turn off the ChatGPTs/Colab-AI and avoid the search bar for this problem ... It *will* help you more.**

In [2]:
import numpy as np

## A simple 2-element array

Let's start with a simple 2-element array, that is something like:

In [3]:
array1a = np.array([2,1])

Here is the way one would sort this. Note the level of detail, a computer cannot think independently, so you need to be very explicit about every step:

    1) Find the first element of the array
    2) Find the second element of the array
    3) Compare the elements
    4) Reorder the array if necerssary
    5) Print the new array
    
**EXERCISE**

Implement these steps to sort this array

In [4]:
# Answer here
a = array1a[0]
b = array1a[1]
if a > b:
    array1a[0] = b
    array1a[1] = a
print(array1a)

[1 2]


## A 3-element array

Does you code work for this 3-element array? Copy and paste your code for the 2-element array below (without changes) and print out the array that you get after "sorting".

In [5]:
array1a = np.array([3,2,1])

In [5]:
# Answer here
a = array1a[0]
b = array1a[1]
if a > b:
    array1a[0] = b
    array1a[1] = a
print(array1a)

[1 2]


Swapping just elements 1 and 2 obviously does not work here. The 3rd element is important as well! But you could continue to swap elements like this:

* Initial array:

[ 3 2 1 ]

* Now we compare and swap elements:

[ <span style='color:Blue'> 3 2 </span> 1 ]  Compare the first two elements

  [ <span style='color:Red'> 2 3 </span> 1 ]  Swap them if necessary

  [ 2 <span style='color:Blue'> 3 1 </span> ]  Compare the next two elements

  [ 2 <span style='color:Red'> 1 3 </span> ]  Swap them if necessary

[ <span style='color:Blue'> 2 1 </span> 3 ]  Return to the begininng and compare the first two elements

  [ <span style='color:Red'> 1 2 </span> 3 ]  Swap them if necessary

  [ 1 <span style='color:Blue'> 2 3 </span> ]  Compare the next two elements

  [ 1 <span style='color:Green'> 2 3 </span> ]  Swap them if necessary

* Final array:

[ 1 2 3 ]

We will use this to code our first sorting algorithm.

To develop a first draft algorithm you do **NOT** need to know much code.

In fact it is often best to approach the problem by drawing, or writing bullet points - these are examples of **Pseudocode**. 

**Pseudocode** is the name for any code-like process. You define the rules so it is a more flexible starting point. E.g. you don't need to remember python syntax (when to use `:`, or when to indent) 

As an example, the instructions we gave above for the 2-element array, is an example of pseudocode. Another example: I might write out first routine for the array [ 2 1 ] as:

    i = first element
    j = second element
    compare i to j
    if i is greater than j
        swap the elements

I (Becky Canning) like to indent in my pseudocode as it is clearer to me - but you might not. It is entirely up to you. (Ian adds to this: I personally do not use pseudocode, but making it "closer" to the language you are writing in, e.g. using python's indentation as Becky does, makes it easier to translate than the instructions we started with).

  

**EXERCISE**


Let's make this more interesting: Adapt your pseudocode so that it would work for *any* size array. Begin by considering the array:

    [ 4 2 3 1 ]
    
Think about how the steps above might apply to this array. It might help to write it out in the same way as we did above. The code below *might* help you start to write this

* Initial array:

[ 4 2 3 1 ]

* Now we compare and swap elements:

[ <span style='color:Blue'> 4 2 </span> 3 1 ] 

...

* Final array:

[ 1 2 3 4 ]


Write out the steps for doing this (maybe convert to a markdown cell for this)

EXAMPLE SOLUTION:

* Initial array:

[ 4 2 3 1 ]

* Compare first two elements and swap if necessary
[ 4 2 3 1 ]
[ 2 4 3 1 ]
* Compare next two elements (4 3) and swap if necessary
[ 2 4 3 1 ]
[ 2 3 4 1 ]
* Compare next two elements (4 1) and swap if necessary
[ 2 3 4 1 ]
[ 2 3 1 4 ]
* Go back to beginning and compare first two elements ( 2 3 ) again and swap if necessary
[ 2 3 1 4 ]
[ 2 3 1 4 ]
* Compare next two elements (3 1) and swap if necessary
[ 2 3 1 4 ]
[ 2 1 3 4 ]
* Compare next two elements (3 4) and swap if necessary
[ 2 1 3 4 ]
[ 2 1 3 4 ]
* Go back to beginning and compare first two elements (2 1) again and swap if necessary
[ 2 1 3 4 ]
[ 1 2 3 4 ]
* Compare next two elements (2 3) and swap if necessary
* Compare next two elements (3 4) and swap if necessary

* Final array:

[ 1 2 3 4 ]


In [7]:
# Write pseudocode for sorting an array of *any* length below
# Pseudocode space
Loop over elements in the array
  i = first element
  j = second element
  compare i to j
    if i is greater than j
      swap elements
  i = second element
  j = third element
  compare i to j
    if i is greater than j
      swap elements
  i = third element
  j = fourth element
  compare i to j
    if i is greater than j
      swap elements
Check if the array is in the right order
  if not loop through again and repeat same steps as above, then do the same sort check
  else end the loop


SyntaxError: invalid syntax (494091378.py, line 3)

For an array with 5 elements ([5,4,3,2,1]) how many times did you need to compare numbers to get the array to be sorted?

In [8]:
# 10

Now convert your pseudocode into python and write our your sorting algorithm.  Print the array at each step in your sorting algorithm.

In [9]:
array1a = np.array([3,2,1])
print("Initial array :", array1a)

# Answer here
for j in range(0,len(array1a)-1):
    for i in range(0,len(array1a)-1):
        a = array1a[i]
        b = array1a[i+1]
        if a > b:
            array1a[i] = b
            array1a[i+1] = a
        print(array1a)


Initial array : [3 2 1]
[2 3 1]
[2 1 3]
[1 2 3]
[1 2 3]


The example algorithm we gave (which you may, or may not, have followed) is called a bubble sort. However, this algorithm is non-optimal (perhaps you reach the correct answer long before you stop iterating the code). Can you think of ways to make this code more efficient? ... We will revisit optimization in detail later on.

In [10]:
array1a = np.array([3,2,1])
print("Initial array :", array1a)

# Answer here
order = np.array(sorted(array1a))

for j in range(0,len(array1a)-1):
    have_swapped_this_pass = False
    for i in range(0,len(array1a)-1):
        a = array1a[i]
        b = array1a[i+1]
        if a > b:
            array1a[i] = b
            array1a[i+1] = a
            have_swapped_this_pass = True
        print(array1a)
    # If I didn't make any swaps this pass the array is in order so stop
    if not have_swapped_this_pass:
        break

Initial array : [3 2 1]
[2 3 1]
[2 1 3]
[1 2 3]
[1 2 3]


## Lessons learned

* Writing a good algorithm is like solving a puzzle - it is about creatively thinking of solutions which will work for the task at hand. 
* Pseudocode is a valuble tool for thinking about how to approach an algorithm - feel free tobring pen and paper to draw/write pseudocode to help you with this course. 
* Figure out the approach you want to take and then think about how to explicitly code that approach in the python language.
* This is where you are better (and more employable) than computer science graduates! Being able to combine your mathematical and analytical skills to creatively problem solve will result in better algorithms than someone who cannot think like this.