# Review

## Basic Numpy

We'll start by reviewing some numpy basics. You can create a numpy array by
 1. Using `np.array` on a list of numbers.
 1. Using `np.arange` or `np.linspace` to create an equally-spaced array.
 1. Using `np.zeros` or `np.ones` to create an array of the same number.

**IMPORTANT**: It's best to vectorize your operations on numpy arrays. That means using numpy functions (and built-in math function like `+`, `-`, `*`, `/`, `**`, etc.) on the *entire array*. This is both clearer and faster than writing a loop over the indexes. Its best to try to do things only in numpy first if you can.

In [1]:
# We'll almost always import numpy as np to save some typing
import numpy as np

In [2]:
# Convert a list to a numpy array
a_list = [1,2,3,4,5,6,7,8,9,10]
a_numpy_array = np.array(a_list)
print(a_numpy_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Create a range of values, just like the range builtin
x_vals = np.arange(0, 2*np.pi, np.pi/6)

# Calculate sin over the entire array
sin_x = np.sin(x_vals)
print(sin_x)

[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01]


In [4]:
# Test the trigonometric identity
np.cos(x_vals)**2 + np.sin(x_vals)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

It is possible to write this as a loop, as done below. But it's more lines, easier to make a mistake, and slower when you have millions of numbers.

In [5]:
result = []
for i in range(len(x_vals)):
    x = x_vals[i]
    result.append(np.cos(x)**2 + np.sin(x)**2)

print(result)

[np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(0.9999999999999999), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0)]


In [6]:
# Nine equally-spaced values from -1 to 1
print(np.linspace(-1, 1, 9))

# Note that printing the numpy array looks different from
# just outputting it (as the last line of the cell)
np.linspace(-1, 1, 9)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

## Slicing Arrays

We'll review how to select portions of the data using *slicing*. This is **very important**, and while we did cover it last year, the idea is confusing and is worth revisiting.

Let's start by defining an array to work with that has floating point numbers of the form 'row.column', so it's easy to see if we've got the right data.

In [7]:
arr10 = np.array([[(ii+0.1*jj) for jj in range(10)] for ii in range(10)])
print(arr10)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


Selecting one entry in the array uses the format `arr[row, col]`. Row 0, column 2 in the matrix above would be `arr10[0, 2]`.

In [8]:
arr10[0,2]

np.float64(0.2)

We can use the same slicing syntax used for lists on arrays as well. We just need to provide a slice for the row and the column. Here are some examples of 1D slices:

 1. `arr[1]` element 1 of arr
 1. `arr[1:4]` elements 1 up to 4 (but not including 4)
 1. `arr[1:]` element 1 to the end
 1. `arr[1:7:2]` element 1, 3, 5, up to 7
 1. `arr[1::2]` element 1, 3, 5, to the end
 1. `arr[:]` all of arr

We can use any of these in the row and the column entry. Let's show this on our 2D array:

In [9]:
# Slicing - All rows, column 1
arr10[:,1]

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [10]:
# Slicing - Row 2, all columns
arr10[2,:]

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [11]:
# Slicing - Row 2, columns 1 through 7, skipping by 2
arr10[2,1:8:2]

array([2.1, 2.3, 2.5, 2.7])

In [12]:
# Slicing - Last row
arr10[-1,:]

array([9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

We can also assign values by putting the slice before an equals sign. Using `:` we can do it to a whole column.

In [13]:
test_arr = arr10.copy()
test_arr[:,5] = 0.
print(test_arr)

[[0.  0.1 0.2 0.3 0.4 0.  0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 0.  1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 0.  2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 0.  3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 0.  4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 0.  5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 0.  6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 0.  7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 0.  8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 0.  9.6 9.7 9.8 9.9]]


## Exercises

Here's some questions for you to practice slicing. Please answer these in the cells below on `test_arr`.

* What is the output of test_arr[1:] and test_arr[:,1]? Please write down what you think first, and then verify below by running this.
* How would you access the element at the second row, third column? What is the value?
* Extract the first two rows, and the last two columns (the output is a 2x2 array)?
* Reverse the order of both the rows and columns?
* Write a function that takes four inputs (max_row, min_row, max_column, min_column) and returns the "subarray" of the original 2D array containing only fields between min_row and max_row, and min_column by max_column. What would the shape of the resulting array be? Check if that's what you have.

`test_arr[1:]` will be the `test_arr` array, missing all the `0.X` entries, it is a 9 by 10 array

`test_arr[:,1]` will be 0.1, 1.1, .... 9.1, it is a 10 by 1 array

In [14]:
print(test_arr[1:])
print(test_arr[:,1])

[[1.  1.1 1.2 1.3 1.4 0.  1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 0.  2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 0.  3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 0.  4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 0.  5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 0.  6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 0.  7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 0.  8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 0.  9.6 9.7 9.8 9.9]]
[0.1 1.1 2.1 3.1 4.1 5.1 6.1 7.1 8.1 9.1]


To access the element at the second row, third column, I would use `test_arr[1,2]`. Its value is 1.2

In [15]:
test_arr[1,2]

np.float64(1.2)

Extract the first two rows, and the last two columns (the output is a 2x2 array)?

In [16]:
test_arr[:2,-2:]

array([[0.8, 0.9],
       [1.8, 1.9]])

Reverse the order of both the rows and columns?

In [17]:
test_arr[::-1,::-1]

array([[9.9, 9.8, 9.7, 9.6, 0. , 9.4, 9.3, 9.2, 9.1, 9. ],
       [8.9, 8.8, 8.7, 8.6, 0. , 8.4, 8.3, 8.2, 8.1, 8. ],
       [7.9, 7.8, 7.7, 7.6, 0. , 7.4, 7.3, 7.2, 7.1, 7. ],
       [6.9, 6.8, 6.7, 6.6, 0. , 6.4, 6.3, 6.2, 6.1, 6. ],
       [5.9, 5.8, 5.7, 5.6, 0. , 5.4, 5.3, 5.2, 5.1, 5. ],
       [4.9, 4.8, 4.7, 4.6, 0. , 4.4, 4.3, 4.2, 4.1, 4. ],
       [3.9, 3.8, 3.7, 3.6, 0. , 3.4, 3.3, 3.2, 3.1, 3. ],
       [2.9, 2.8, 2.7, 2.6, 0. , 2.4, 2.3, 2.2, 2.1, 2. ],
       [1.9, 1.8, 1.7, 1.6, 0. , 1.4, 1.3, 1.2, 1.1, 1. ],
       [0.9, 0.8, 0.7, 0.6, 0. , 0.4, 0.3, 0.2, 0.1, 0. ]])

Write a function that takes four inputs (max_row, min_row, max_column, min_column) and returns the "subarray" of the original 2D array containing only fields between min_row and max_row, and min_column by max_column. What would the shape of the resulting array be? Check if that's what you have.

In [18]:
def subarray(max_row, min_row, max_column, min_column):
    return test_arr[min_row:max_row,min_column:max_column]

The resulting shape would be (max(max_row - min_row, 0)) by (max(max_column - min_column, 0))

In [19]:
# This testing is potentially overkill, but takes every possible combination of min/max row/column and asserts that the output shape is what we said in the previous cell

for max_row in range(0, 10):
    for min_row in range(0, 10):
        for max_column in range(0, 10):
            for min_column in range(0, 10):
                subarr = subarray(max_row, min_row, max_column, min_column)
                assert subarr.shape == (max(max_row - min_row,0), max(max_column - min_column, 0))

# This uses the fact that if we take a slice where the 'end' is less than the 'start', we get a zero-sized array, rather than an error