# Matrices in numpy

We explored matrices in MATLAB last year, but didn't do this in python ... This was because you hadn't covered matrices in the math modules by that point, so let's do this now.

## Transposing and reshaping arrays

Let's move on now to consider some multi-dimension arrays. Let's first consider the following 12 x 10 array of random numbers uniformly distributed between 0 and 10:

In [1]:
import numpy as np
np.random.seed(0)
nums = np.random.random_sample(size=[12,10]) * 10
print (nums)

[[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113
  4.37587211 8.91773001 9.63662761 3.83441519]
 [7.91725038 5.2889492  5.68044561 9.25596638 0.71036058 0.871293
  0.20218397 8.32619846 7.78156751 8.70012148]
 [9.78618342 7.99158564 4.61479362 7.80529176 1.18274426 6.39921021
  1.43353287 9.44668917 5.21848322 4.1466194 ]
 [2.64555612 7.74233689 4.56150332 5.68433949 0.187898   6.17635497
  6.12095723 6.16933997 9.43748079 6.81820299]
 [3.59507901 4.37031954 6.97631196 0.60225472 6.66766715 6.7063787
  2.10382561 1.28926298 3.15428351 3.63710771]
 [5.7019677  4.38601513 9.88373838 1.02044811 2.08876756 1.61309518
  6.53108325 2.53291603 4.66310773 2.44425592]
 [1.58969584 1.10375141 6.56329589 1.38182951 1.96582362 3.68725171
  8.2099323  0.97101276 8.37944907 0.96098408]
 [9.76459465 4.68651202 9.76761088 6.0484552  7.39263579 0.39187792
  2.82806963 1.20196561 2.96140198 1.18727719]
 [3.17983179 4.14262995 0.64147496 6.92472119 5.66601454 2.65389491
  5.23248053 0.

To transpose this array is quite simple, numpy supplies a `.T` property:

In [2]:
print (nums.T)

[[5.48813504 7.91725038 9.78618342 2.64555612 3.59507901 5.7019677
  1.58969584 9.76459465 3.17983179 3.18568952 6.77816537 4.47125379]
 [7.15189366 5.2889492  7.99158564 7.74233689 4.37031954 4.38601513
  1.10375141 4.68651202 4.14262995 6.6741038  2.70007973 8.46408672]
 [6.02763376 5.68044561 4.61479362 4.56150332 6.97631196 9.88373838
  6.56329589 9.76761088 0.64147496 1.31797862 7.35194022 6.99479275]
 [5.44883183 9.25596638 7.80529176 5.68433949 0.60225472 1.02044811
  1.38182951 6.0484552  6.92472119 7.16327204 9.62188545 2.97436951]
 [4.23654799 0.71036058 1.18274426 0.187898   6.66766715 2.08876756
  1.96582362 7.39263579 5.66601454 2.89406093 2.48753144 8.1379782 ]
 [6.45894113 0.871293   6.39921021 6.17635497 6.7063787  1.61309518
  3.68725171 0.39187792 2.65389491 1.83191362 5.76157334 3.96505741]
 [4.37587211 0.20218397 1.43353287 6.12095723 2.10382561 6.53108325
  8.2099323  2.82806963 5.23248053 5.86512935 5.92041931 8.81103197]
 [8.91773001 8.32619846 9.44668917 6.16933

If we want to reshape the array we can use numpy's `reshape` function. For example if I want to "flatten" this array (note there is also a `flatten` function, but `reshape` is more general), we could do:

In [3]:
np.reshape(nums, (120,))

array([5.48813504, 7.15189366, 6.02763376, 5.44883183, 4.23654799,
       6.45894113, 4.37587211, 8.91773001, 9.63662761, 3.83441519,
       7.91725038, 5.2889492 , 5.68044561, 9.25596638, 0.71036058,
       0.871293  , 0.20218397, 8.32619846, 7.78156751, 8.70012148,
       9.78618342, 7.99158564, 4.61479362, 7.80529176, 1.18274426,
       6.39921021, 1.43353287, 9.44668917, 5.21848322, 4.1466194 ,
       2.64555612, 7.74233689, 4.56150332, 5.68433949, 0.187898  ,
       6.17635497, 6.12095723, 6.16933997, 9.43748079, 6.81820299,
       3.59507901, 4.37031954, 6.97631196, 0.60225472, 6.66766715,
       6.7063787 , 2.10382561, 1.28926298, 3.15428351, 3.63710771,
       5.7019677 , 4.38601513, 9.88373838, 1.02044811, 2.08876756,
       1.61309518, 6.53108325, 2.53291603, 4.66310773, 2.44425592,
       1.58969584, 1.10375141, 6.56329589, 1.38182951, 1.96582362,
       3.68725171, 8.2099323 , 0.97101276, 8.37944907, 0.96098408,
       9.76459465, 4.68651202, 9.76761088, 6.0484552 , 7.39263

This indicates that this should become a 1D array with 120 entries. We could also make this a 4 x 30 array or a 30 x 4 array with something like:

In [4]:
np.reshape(nums, (4,30))

array([[5.48813504, 7.15189366, 6.02763376, 5.44883183, 4.23654799,
        6.45894113, 4.37587211, 8.91773001, 9.63662761, 3.83441519,
        7.91725038, 5.2889492 , 5.68044561, 9.25596638, 0.71036058,
        0.871293  , 0.20218397, 8.32619846, 7.78156751, 8.70012148,
        9.78618342, 7.99158564, 4.61479362, 7.80529176, 1.18274426,
        6.39921021, 1.43353287, 9.44668917, 5.21848322, 4.1466194 ],
       [2.64555612, 7.74233689, 4.56150332, 5.68433949, 0.187898  ,
        6.17635497, 6.12095723, 6.16933997, 9.43748079, 6.81820299,
        3.59507901, 4.37031954, 6.97631196, 0.60225472, 6.66766715,
        6.7063787 , 2.10382561, 1.28926298, 3.15428351, 3.63710771,
        5.7019677 , 4.38601513, 9.88373838, 1.02044811, 2.08876756,
        1.61309518, 6.53108325, 2.53291603, 4.66310773, 2.44425592],
       [1.58969584, 1.10375141, 6.56329589, 1.38182951, 1.96582362,
        3.68725171, 8.2099323 , 0.97101276, 8.37944907, 0.96098408,
        9.76459465, 4.68651202, 9.76761088, 6.

In [5]:
np.reshape(nums, (30,4))

array([[5.48813504, 7.15189366, 6.02763376, 5.44883183],
       [4.23654799, 6.45894113, 4.37587211, 8.91773001],
       [9.63662761, 3.83441519, 7.91725038, 5.2889492 ],
       [5.68044561, 9.25596638, 0.71036058, 0.871293  ],
       [0.20218397, 8.32619846, 7.78156751, 8.70012148],
       [9.78618342, 7.99158564, 4.61479362, 7.80529176],
       [1.18274426, 6.39921021, 1.43353287, 9.44668917],
       [5.21848322, 4.1466194 , 2.64555612, 7.74233689],
       [4.56150332, 5.68433949, 0.187898  , 6.17635497],
       [6.12095723, 6.16933997, 9.43748079, 6.81820299],
       [3.59507901, 4.37031954, 6.97631196, 0.60225472],
       [6.66766715, 6.7063787 , 2.10382561, 1.28926298],
       [3.15428351, 3.63710771, 5.7019677 , 4.38601513],
       [9.88373838, 1.02044811, 2.08876756, 1.61309518],
       [6.53108325, 2.53291603, 4.66310773, 2.44425592],
       [1.58969584, 1.10375141, 6.56329589, 1.38182951],
       [1.96582362, 3.68725171, 8.2099323 , 0.97101276],
       [8.37944907, 0.96098408,

In all cases the order of the data is preserved. There is a bit more information on reshaping an array here:

https://www.w3resource.com/numpy/manipulation/reshape.php

If you try to do something invalid, the code will fail:

In [6]:
try:
    np.reshape(nums, (30,10))
except ValueError as err:
    print(err)

cannot reshape array of size 120 into shape (30,10)


## EXERCISE

Create a 2D array (x,y) whose values should be equal to $x**2 + y$ (so the value at `[0,1]` would be 1, the value at `[2,4]` would be $2^2 + 4 = 8$ and so on). The size of this array should be 42 x 20.

Take the transpose of this array. Now if this new array has coordinates (x1,y1) what is the value at x1 = 4, y1=5 going to be?

There are a number of different 2D shapes that you can reshape this array into (I counted 32). How many valid different sizes can you reshape this array into.

Reshape this array into a 5D shape, where no dimension has a size equal to 1.

## Matrix operations

A 2D array in numpy can be treated as a matrix, but unlike in MATLAB, it will *not* be treated mathematically as a matrix unless you tell it. For example doing `a * b` will perform elementwise multiplication, not matrix multiplication. BUT, we can still do all matrix stuff in MATLAB in numpy just as easily.

First let's show elementwise multiplication:

In [10]:
nums1 = np.random.random_sample(size=[12,10]) * 10
nums2 = np.random.random_sample(size=[12,10]) * 10
nums3 = np.random.random_sample(size=[10,10]) * 10

prod = nums1 * nums2
# To multiply two numpy arrays they must be the same shape, and then every element is multiplied by its corresponding
# element in the other array. That's not how matrix multiplication works
print (prod.shape)
print()

# This won't work, they are not the same shape!
try:
    prod2 = nums1 * nums3
except ValueError as err:
    print(err)


(12, 10)

operands could not be broadcast together with shapes (12,10) (10,10) 


Now let's show matrix multiplication, we use the `@` operator to do this:

In [11]:
# The @ indicates matrix multiplication, nums1 can be multiplied by nums3
mult1 = nums1 @ nums3

print(mult1)

# But nums1 cannot be multiplied by nums2.
# I cannot multiply a 12x10 matrix by a 12x10 matrix!
# Let's catch this error and continue. Python's try/except can be used for this
# https://docs.python.org/3/tutorial/errors.html

try:
    nums1 @ nums2
except ValueError as err:
    print ("This doesn't work! The [not particularly helpful] error message says:")
    print (err)

# But I can multiply a 12x10 matrix by a 10x12 matrix (the resulting matrix should be 12 x 12.)
# OR I can multiply a 10x12 matrix by a 12x10 matrix (resulting in a 10x10 matrix)

prod1 = nums1 @ nums2.T
prod2 = nums1.T @ nums2

print (prod1.shape, prod2.shape)

[[194.19872992 323.76528078 269.90001023 256.59623967 266.65411148
  268.07233792 307.53394386 201.36703269 290.73757293 266.98396255]
 [186.87437507 364.05132317 207.01159042 217.82275719 266.2129797
  205.64735424 302.87286885 181.84545079 312.21562361 258.04946699]
 [206.25480043 485.05758491 271.65819963 335.8318468  377.87966333
  318.71636229 385.02726837 232.66971934 399.43871757 357.41591532]
 [196.74690349 281.61871556 198.63747378 210.39059441 175.98451147
  201.20781872 279.64418302 179.82089709 229.86097634 222.18984637]
 [193.86793965 377.53813833 260.07514993 318.95991392 290.97189697
  299.23471434 311.84209588 220.83252834 310.10716687 272.36668002]
 [145.41271768 299.38856027 164.3070563  192.02313896 227.18648753
  168.02146319 233.14497149 147.09512841 276.76462279 178.9653195 ]
 [238.00945252 368.45246659 242.31302848 258.93746315 283.7999495
  234.78560296 322.25325694 200.55643211 321.72119237 250.05794702]
 [117.73806627 268.46602483 122.1584458  230.22005044 204

We can also compute the eigenvalues and eigenvectors of a square 2D array :

In [12]:
# Make a diagonal matrix
nums1 = np.zeros([3,3])
nums1[0,0] = 1.
nums1[1,1] = 2.
nums1[2,2] = 3.
print(nums1)
# Or equivalently
print (np.diag([1.,2.,3.]))

evals, evecs = np.linalg.eig(nums1)

print (evals)
print (evecs)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## EXERCISE

Generate a 2D 10x10 matrix of random numbers. Compute the eigenvectors and eigenvalues of this matrix.

Now try again but this time generate a symmetric matrix (where the value at `[x,y]` is equal to the value at `[y,x]`). What do you notice is different? Why is this?

Confirm that the eigenvectors and eigenvalues are correct