# Methods of numpy arrays.

The numpy array class defines a number of `methods` for easily accessing information about the numpy array. Let's explore a few of these methods now.

## The `.any` and `.all` method

The `any` method can be used to check if at least one element in a boolean array is True. For example if we want to go back to our `some_numbers` array, and ask if it contains any number greater than 20 we can do:

In [1]:
import numpy as np

some_numbers = np.array([1,10,2,20,3,30,4,40,5,50,6,60])

if (some_numbers > 20).any():
    print ("There is at least one value in some_numbers larger than 20")

There is at least one value in some_numbers larger than 20


Similarly we can use the `all` method to ask if all numbers in `some_numbers` are larger than 20:

In [2]:
some_numbers = np.array([1,10,2,20,3,30,4,40,5,50,6,60])

if (some_numbers > 20).all():
    print ("All numbers in some_numbers are larger than 20")
else:
    print ("Not all the numbers in some_numbers are larger than 20")

Not all the numbers in some_numbers are larger than 20


In both cases, these methods can also run on non boolean arrays:

In [3]:
print (some_numbers.all())

True


In such cases it will be checking the "truth value" of each entry in the array. 0, or 0.0 or `''` are False for integers, floats and strings respectively, anything else is True. This is the same as running `bool(value)` on all values in the array and then checking if any, or all, are True.

Let's take our pandas example again before setting some exercises:

In [4]:
import numpy as np
import pandas as pd
def func_makedata(a):
    x1 = a**2
    y1 = np.cos(a)
    z1 = 3*a**2 
    return x1, y1, z1

aa = np.linspace(0.,10.,50)
x1, y1, z1 = func_makedata(aa)

data_dict = {}
data_dict['aa'] = aa
data_dict['x1'] = x1
data_dict['y1'] = y1
data_dict['z1'] = z1
pd_dataframe = pd.DataFrame(data_dict)
pd_dataframe

aa          x1        y1          z1
0    0.000000    0.000000  1.000000    0.000000
1    0.204082    0.041649  0.979248    0.124948
2    0.408163    0.166597  0.917851    0.499792
3    0.612245    0.374844  0.818360    1.124531
4    0.816327    0.666389  0.684902    1.999167
5    1.020408    1.041233  0.523018    3.123698
6    1.224490    1.499375  0.339426    4.498126
7    1.428571    2.040816  0.141746    6.122449
8    1.632653    2.665556 -0.061817    7.996668
9    1.836735    3.373594 -0.262815   10.120783
10   2.040816    4.164931 -0.452904   12.494794
11   2.244898    5.039567 -0.624196   15.118701
12   2.448980    5.997501 -0.769580   17.992503
13   2.653061    7.038734 -0.883023   21.116202
14   2.857143    8.163265 -0.959816   24.489796
15   3.061224    9.371095 -0.996772   28.113286
16   3.265306   10.662224 -0.992357   31.986672
17   3.469388   12.036651 -0.946755   36.109954
18   3.673469   13.494377 -0.861857   40.483132
19   3.877551   15.035402 -0.741188   45.106206
20   4.081633   16.659725 -0.589756   49.979175
21   4.285714   18.367347 -0.413846   55.102041
22   4.489796   20.158267 -0.220759   60.474802
23   4.693878   22.032486 -0.018510   66.097459
24   4.897959   23.990004  0.184507   71.970012
25   5.102041   26.030820  0.379866   78.092461
26   5.306122   28.154935  0.559459   84.464806
27   5.510204   30.362349  0.715832   91.087047
28   5.714286   32.653061  0.842494   97.959184
29   5.918367   35.027072  0.934189  105.081216
30   6.122449   37.484382  0.987110  112.453145
31   6.326531   40.024990  0.999061  120.074969
32   6.530612   42.648896  0.969546  127.946689
33   6.734694   45.356102  0.899790  136.068305
34   6.938776   48.146606  0.792688  144.439817
35   7.142857   51.020408  0.652686  153.061224
36   7.346939   53.977509  0.485594  161.932528
37   7.551020   57.017909  0.298348  171.053728
38   7.755102   60.141608  0.098719  180.424823
39   7.959184   63.348605 -0.105008  190.045814
40   8.163265   66.638900 -0.304376  199.916701
41   8.367347   70.012495 -0.491112  210.037484
42   8.571429   73.469388 -0.657463  220.408163
43   8.775510   77.009579 -0.796527  231.028738
44   8.979592   80.633070 -0.902531  241.899209
45   9.183673   84.339858 -0.971075  253.019575
46   9.387755   88.129946 -0.999315  264.389838
47   9.591837   92.003332 -0.986078  276.009996
48   9.795918   95.960017 -0.931914  287.880050
49  10.000000  100.000000 -0.839072  300.000000

## EXERCISES

* Are there any values in $\mathrm{y1}$ for which $\cos^{-1}(y1) > 3.0$ (radians)
* Do all of the values of $(x1 - 50) * (z1 - 150)$ have a magnitude smaller than 5000?

In [5]:
print((np.arccos(y1) < 3.0).any())
print((abs((x1-50) * (z1-150)) < 5000).all())

True
False


## The `np.where` function

Consider again our list of `some_numbers`. Let's say that we have a problem that asks: For your list of numbers create a new list storing $x^2$ if $x$ is smaller than 10 or $x^{0.5}$ is x is larger than or equal to 10. This is a perfect example for numpy's `where` function:

In [6]:
# Let's let numpy explain what this function does first
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [7]:
some_numbers = np.array([1,10,2,20,3,30,4,40,5,50,6,60])
np.where(some_numbers >= 10, some_numbers**0.5, some_numbers**2)

array([ 1.        ,  3.16227766,  4.        ,  4.47213595,  9.        ,
        5.47722558, 16.        ,  6.32455532, 25.        ,  7.07106781,
       36.        ,  7.74596669])

Alternatively, if we just run this with the first argument:

In [8]:
np.where(some_numbers >= 10)[0]

array([ 1,  3,  5,  7,  9, 11])

It returns the indexes of the points where some_numbers is larger than or equal to 10. This can also be used to index, so we can do:

In [9]:
# Returns the points at positions 1, 3, 5, 7, 9 and 11
some_numbers[np.where(some_numbers >= 10)[0]]

array([10, 20, 30, 40, 50, 60])

This is equivalent to having done:

In [10]:
some_numbers[some_numbers >= 10]

array([10, 20, 30, 40, 50, 60])

But sometimes we want to know the indexes.

## EXERCISE

Create an array out of some_numbers from the following condition.

* If the number is larger than 20, store $x^3$. If the number is smaller than or equal to 20, store 1.

Then try the following:

* If the number is larger than 20, store $x^3$. If the number is larger than 4 but smaller than or equal to 20 store $x$, otherwise store 1.

In [11]:
np.where(some_numbers > 20, some_numbers ** 3, 1)

array([     1,      1,      1,      1,      1,  27000,      1,  64000,
            1, 125000,      1, 216000])

In [12]:
np.where(some_numbers > 20, some_numbers ** 3, np.where(some_numbers > 4, some_numbers, 1))

array([     1,     10,      1,     20,      1,  27000,      1,  64000,
            5, 125000,      6, 216000])