# Numpy

We used numpy extensively last year in attempting data science problems. It will continue to be very important. Let's briefly recap

In [1]:
import numpy as np # Import numpy to use it

## Numpy Arrays

We create numpy arrays as follows

In [2]:
arr1 = np.array(range(10))
print(type(arr1), arr1)

<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]


In [3]:
arr2 = np.arange(10)
print(type(arr1), arr1)

<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]


In [4]:
start, stop, step = 2, 18, 4
arr3 = np.arange(start, stop, step)
print(arr3)

[ 2  6 10 14]


Here are a few special kinds of arrays: zeros, ones, and 'full', which fills with a single value.

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones((4,2)) 

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.full((3,5), 7.)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

Note that these can be matrices, not just lists. We can set, and calculate, their shape. The first number is the rows, second is the columns.

In [8]:
matrix1 = np.ones((3,5))
print(matrix1)
print(matrix1.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


The shape is what's called a 'tuple'. It's very similar to a list, but it's immutable (can't be changed).

In [9]:
tst = (1,2)
print(type(tst))
tst.append(3)

<class 'tuple'>


AttributeError: 'tuple' object has no attribute 'append'

In [10]:
# We can also make an evenly spaced array of a given length
np.linspace(-1., 2., 5)

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ])

## Slicing and Transposing Arrays

We'll start by defining an array to work with that has floating point numbers of the form 'row.column', so it's easy to see if we've got the right data.

In [11]:
inp_data = []
for ii in range(10):
    curr_data = []
    for jj in range(10):
        curr_data.append(ii+0.1*jj)
    inp_data.append(curr_data)

arr10 = np.array(inp_data)

In [12]:
print(arr10)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


In [13]:
# Slicing - Take all rows in column 1
arr10[:,1]

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [14]:
# Slicing - Take all columns in row 2
arr10[2,:]

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [15]:
# Slicing - Take Row 2, columns 1 through 5
arr10[2,1:6]

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [16]:
# Slicing - Row 2, columns 1 through 7, skipping by 2
arr10[2,1:8:2]

array([2.1, 2.3, 2.5, 2.7])

In [17]:
# Slicing - Last row
arr10[-1,:]

array([9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

***Slicing is vital!! You need to be comfortable doing this***

**Exercise**: Get all values in column 4.

In [18]:
arr10[:,4]

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

**Exercise**: Get all values in columns 4 and 5.

In [20]:
arr10[:,4:6]

array([[0.4, 0.5],
       [1.4, 1.5],
       [2.4, 2.5],
       [3.4, 3.5],
       [4.4, 4.5],
       [5.4, 5.5],
       [6.4, 6.5],
       [7.4, 7.5],
       [8.4, 8.5],
       [9.4, 9.5]])

**Exercise**: Get values in row 1,3,and 5, columns 4 through 7.

In [22]:
arr10[(1,3,5),4:8]

array([[1.4, 1.5, 1.6, 1.7],
       [3.4, 3.5, 3.6, 3.7],
       [5.4, 5.5, 5.6, 5.7]])

## Other operations

If you want to exchange rows and columns, take the transpose: `arr.T`.

In [23]:
arr10.T

array([[0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ],
       [0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1],
       [0.2, 1.2, 2.2, 3.2, 4.2, 5.2, 6.2, 7.2, 8.2, 9.2],
       [0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3],
       [0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4],
       [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5],
       [0.6, 1.6, 2.6, 3.6, 4.6, 5.6, 6.6, 7.6, 8.6, 9.6],
       [0.7, 1.7, 2.7, 3.7, 4.7, 5.7, 6.7, 7.7, 8.7, 9.7],
       [0.8, 1.8, 2.8, 3.8, 4.8, 5.8, 6.8, 7.8, 8.8, 9.8],
       [0.9, 1.9, 2.9, 3.9, 4.9, 5.9, 6.9, 7.9, 8.9, 9.9]])